import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// 分别构建 JS 和 CSS
const jsContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

const cssContext = await esbuild.context({
	entryPoints: ["styles.css"],
	bundle: true,
	loader: {
		".css": "css"
	},
	outfile: "styles.css",
	minify: prod,
	allowOverwrite: true
});

if (prod) {
	await jsContext.rebuild();
	await cssContext.rebuild();
	process.exit(0);
} else {
	await jsContext.watch();
	await cssContext.watch();
} 